local CommandCompletion = {}

CommandCompletion.Commands = {
    "/achievements", "/aclearcompare", "/acompare", "/addraidlooter", "/advloot", "/afk", "/aggrolock", "/aggrometer",
    "/alarm", "/alternateadv", "/anonymous", "/assist", "/attack", "/auction", "/autobank", "/autoconsent",
    "/autofire", "/autoinventory", "/autojoin", "/autoskill", "/autosplit", "/bandolier", "/barter", "/bazaar",
    "/beta", "/betabuff", "/blockspell", "/bodytint", "/book", "/bugreport", "/buyer", "/calendar",
    "/camp", "/cast", "/changefamiliarname", "/changemercname", "/changename", "/changepetname", "/channel", "/charinfo",
    "/chat", "/chatfontsize", "/claim", "/clearallchat", "/clearchat", "/clearmarks", "/clickthrough", "/combatmusic",
    "/compareexpedraid", "/comparetaskraid", "/consent", "/consider", "/copylayout", "/corpse", "/corpsedrag", "/corpsedrop",
    "/decaycorpse", "/decline", "/delegategmarknpc", "/delegategmasterlooter", "/delegatermarknpc", "/delegatermasterlooter", "/deny", "/destroyitem",
    "/disband", "/discipline", "/dismount", "/doability", "/duck", "/duel", "/dynamiclights", "/dzaddplayer",
    "/dzhelp", "/dzlisttimers", "/dzmakeleader", "/dzplayerlist", "/dzquit", "/dzremoveplayer", "/dzswapplayer", "/emote",
    "/exit", "/extralife", "/faction", "/familiar", "/fastdrop", "/feedback", "/filter", "/finditem",
    "/findpc", "/follow", "/fontface", "/friends", "/fsay", "/fullscreen", "/gems", "/getguildmotd",
    "/gmarknpc", "/groupleader", "/grouproles", "/gsay", "/guidehelp", "/guildcreate", "/guilddelete", "/guilddemote",
    "/guildinvite", "/guildleader", "/guildmotd", "/guildpromote", "/guildremove", "/guildsay", "/guildstatus", "/hail",
    "/help", "/hidecorpses", "/hidemodels", "/hotbutton", "/ignore", "/indicator", "/inspect", "/inspectbuffs",
    "/invite", "/itemoverflow", "/keyrings", "/keys", "/kickplayers", "/language", "/leaverealestate", "/lfgroup",
    "/lfguild", "/loadskin", "/location", "/log", "/loginterval", "/loot", "/lootnodrop", "/makeleader",
    "/makeraidleader", "/map", "/marketplace", "/mcicontrol", "/melody", "/memspellset", "/memspellslot", "/mercassist",
    "/merclog", "/mercswitch", "/mercwindows", "/mixahead", "/motd", "/mousespeed", "/mp3", "/netstats",
    "/note", "/offlinemode", "/ooc", "/open", "/outputfile", "/overseer", "/particledensity", "/pause",
    "/pet", "/petition", "/pickzone", "/pickzonefewestplayers", "/played", "/quit", "/racechange", "/raidaccept",
    "/raiddecline", "/raiddisband", "/raidinvite", "/raidwindow", "/random", "/realestate", "/removeraidlooter", "/renameguild",
    "/reply", "/report", "/rewards", "/rewind", "/rmarknpc", "/roleplay", "/rsay", "/rtarget",
    "/run", "/safelock", "/say", "/servertransfer", "/setloottype", "/setstartcity", "/shadows", "/shield",
    "/shieldgroup", "/shout", "/showgrass", "/shownames", "/shownpcnames", "/showspelleffects", "/sit", "/split",
    "/stance", "/stand", "/stopcast", "/stopdisc", "/stopsocial", "/stopsong", "/stoptracking", "/surname",
    "/swarm", "/system", "/target", "/targetoftarget", "/taskaddplayer", "/taskhelp", "/taskmakeleader", "/taskoverlay",
    "/taskplayerlist", "/taskquit", "/taskremoveplayer", "/tasktimers", "/tell", "/testbuffme", "/testcopy", "/time",
    "/toggleinspect", "/trackfilter", "/trackmercs", "/trackpets", "/trackplayers", "/tracksort", "/trader", "/tribute",
    "/trophy", "/ttell", "/ui", "/url", "/useadvlooting", "/useitem", "/usercolor", "/usetarget",
    "/usurp", "/vgroup", "/viewport", "/vplay", "/vraid", "/vtell", "/waypoint", "/who",
    "/whotarget", "/www", "/xtarget", "/yell", "#acceptrules", "#advnpcspawn", "#aggrozone ", "#ai", "#appearance",
    "#appearanceeffects", "#apply_shared_memory", "#attack", "#augmentitem", "#ban", "#bugs", "#bot", "#camerashake",
    "#castspell", "#chat", "#clearxtargets", "#copycharacter", "#corpse", "#corpsefix", "#countitem", "#damage", "#databuckets",
    "#dbspawn2", "#delacct", "#delpetition", "#depop", "#depopzone", "#devtools", "#disablerecipe", "#disarmtrap", "#door",
    "#doanim", "#dye", "#dz", "#dzkickplayers", "#editmassrespawn", "#emote", "#emptyinventory", "#enablerecipe", "#entityvariable",
    "#exptoggle", "#faction", "#factionassociation", "#feature", "#size", "#find", "#fish", "#fixmob", "#flagedit",
    "#fleeinfo", "#forage", "#gearup", "#giveitem", "#givemoney", "#gmzone", "#goto", "#grantaa", "#grid", "#guild", "#help",
    "#hotfix", "#hp", "#instance", "#interrogateinv", "#interrupt", "#invsnapshot", "#ipban", "#kick", "#kill",
    "#killallnpcs", "#list", "#lootsim", "#load_shared_memory", "#loc", "#logs", "#makepet", "#memspell", "#merchantshop",
    "#modifynpcstat", "#movechar", "#movement", "#myskills", "#mysql", "#mystats", "#npccast", "#npcedit", "#npceditmass",
    "#npcemote", "#npcloot", "#npcsay", "#npcshout", "#npcspawn", "#npctypespawn", "#nudge", "#nukebuffs", "#nukeitem",
    "#object", "#opcode", "#parcels", "#path", "#peqzone", "#petitems", "#picklock", "#profanity", "#push", "#raidloot",
    "#randomfeatures", "#refreshgroup", "#reload", "#rq", "#rl", "#removeitem", "#repop", "#resetaa", "#resetaa_timer",
    "#resetdisc_timer", "#revoke", "#roambox", "#rules", "#save", "#scale", "#scribespell", "#scribespells",
    "#sendzonespawns", "#sensetrap", "#serverrules", "#set", "#show", "#shutdown", "#spawn", "#spawneditmass", "#spawnfix",
    "#stun", "#summon", "#summonburiedplayercorpse", "#summonitem", "#suspend", "#suspendmulti", "#takeplatinum", "#task",
    "#petname", "#traindisc", "#tune", "#undye", "#unmemspell", "#unmemspells", "#unscribespell", "#unscribespells",
    "#untraindisc", "#untraindiscs", "#wc", "#worldshutdown", "#wp", "#wpadd", "#worldwide", "#zone", "#zonebootup",
    "#zoneinstance", "#zoneshutdown", "#zsave",
}

CommandCompletion.Zones = {
    "qeynos", "qeynos2", "qrg", "qeytoqrg", "highkeep", "freportn", "freportw", "freporte",
    "runnyeye", "qey2hh1", "northkarana", "southkarana", "eastkarana", "beholder", "blackburrow",
    "paw", "rivervale", "kithicor", "commons", "ecommons", "erudnint", "erudnext", "nektulos",
    "cshome", "lavastorm", "nektropos", "halas", "everfrost", "soldunga", "soldungb", "misty",
    "nro", "southro", "befallen", "oasis", "tox", "hole", "neriaka", "neriakb", "neriakc",
    "neriakd", "najena", "qcat", "innothule", "feerrott", "cazicthule", "oggok", "rathemtn",
    "lakerathe", "grobb", "aviak", "gfaydark", "akanon", "steamfont", "lfaydark", "crushbone",
    "mistmoore", "kaladima", "felwithea", "felwitheb", "unrest", "kedge", "guktop", "gukbottom",
    "kaladimb", "butcher", "oot", "cauldron", "airplane", "fearplane", "permafrost", "kerraridge",
    "paineel", "hateplane", "arena", "soltemple", "erudsxing", "stonebrunt", "warrens", "erudsxing2",
    "bazaar", "bazaar2", "arena2", "jaggedpine", "nedaria", "tutorial", "load", "load2", "hateplaneb",
    "shadowrest", "tutoriala", "tutorialb", "clz", "poknowledge", "soldungc", "guildlobby", "barter",
    "takishruins", "freeporteast", "freeportwest", "freeportsewers", "northro", "southro", "highpasshold",
    "commonlands", "oceanoftears", "kithforest", "befallenb", "highpasskeep", "innothuleb", "toxxulia",
    "mistythicket", "steamfontmts", "dragonscalea", "crafthalls", "weddingchapel", "weddingchapeldark",
    "dragoncrypt", "arttest", "fhalls", "apprentice", "fieldofbone", "warslikswood", "droga", "cabwest",
    "swampofnohope", "firiona", "lakeofillomen", "dreadlands", "burningwood", "kaesora", "sebilis", "citymist",
    "skyfire", "frontiermtns", "overthere", "emeraldjungle", "trakanon", "timorous", "kurn", "karnor",
    "chardok", "dalnir", "charasis", "cabeast", "nurga", "veeshan", "veksar", "chardokb", "iceclad",
    "frozenshadow", "velketor", "kael", "skyshrine", "thurgadina", "eastwastes", "cobaltscar", "greatdivide",
    "wakening", "westwastes", "crystal", "necropolis", "templeveeshan", "sirens", "mischiefplane",
    "growthplane", "sleeper", "thurgadinb", "shadowhaven", "nexus", "echo", "acrylia", "sharvahl", "paludal",
    "fungusgrove", "vexthal", "sseru", "katta", "netherbian", "ssratemple", "griegsend", "thedeep",
    "shadeweaver", "hollowshade", "grimling", "mseru", "letalis", "twilight", "thegrey", "tenebrous",
    "maiden", "dawnshroud", "scarlet", "umbral", "akheva", "codecay", "pojustice", "potranquility",
    "ponightmare", "podisease", "poinnovation", "potorment", "povalor", "bothunder", "postorms",
    "hohonora", "solrotower", "powar", "potactics", "poair", "powater", "pofire", "poeartha", "potimea",
    "hohonorb", "nightmareb", "poearthb", "potimeb", "gunthak", "dulak", "torgiran", "nadox", "hatesfury",
    "guka", "ruja", "taka", "mira", "mmca", "gukb", "rujb", "takb", "mirb", "mmcb", "gukc", "rujc", "takc",
    "mirc", "mmcc", "gukd", "rujd", "takd", "mird", "mmcd", "guke", "ruje", "take", "mire", "mmce", "gukf",
    "rujf", "takf", "mirf", "mmcf", "gukg", "rujg", "takg", "mirg", "mmcg", "gukh", "rujh", "takh", "mirh",
    "mmch", "ruji", "taki", "miri", "mmci", "rujj", "takj", "mirj", "mmcj", "abysmal", "natimbi", "qinimi",
    "riwwi", "barindu", "ferubi", "snpool", "snlair", "snplant", "sncrematory", "tipt", "vxed", "yxtta",
    "uqua", "kodtaz", "ikkinz", "qvic", "inktuta", "txevu", "tacvi", "qvicb", "wallofslaughter",
    "bloodfields", "draniksscar", "causeway", "chambersa", "chambersb", "chambersc", "chambersd", "chamberse",
    "chambersf", "provinggrounds", "anguish", "dranikhollowsa", "dranikhollowsb", "dranikhollowsc",
    "dranikhollowsd", "dranikhollowse", "dranikhollowsf", "dranikhollowsg", "dranikhollowsh",
    "dranikhollowsi", "dranikhollowsj", "dranikcatacombsa", "dranikcatacombsb", "dranikcatacombsc",
    "draniksewersa", "draniksewersb", "draniksewersc", "riftseekers", "harbingers", "dranik", "broodlands",
    "stillmoona", "stillmoonb", "thundercrest", "delvea", "delveb", "thenest", "guildhall"
}

--[[CommandCompletion.Group = {
    mq.TLO.Group.Member(0).Name(),
    mq.TLO.Group.Member(1).Name(),
    mq.TLO.Group.Member(2).Name(),
    mq.TLO.Group.Member(3).Name(),
    mq.TLO.Group.Member(4).Name(),
    mq.TLO.Group.Member(5).Name(),
}--]]

return CommandCompletion
